### ISSUE TITLE
Add no-confirm option

### ISSUE THREAD

**Issue by TheBlackKoala** [Jeselnik/rb-scrobbler#2]
Running rb-scrobbler from a script is un-practical when you need to interact with the script to decide wether or not to delete the file. A --delete/keep and/or --no-confirm would be a great way to handle this.

**Comment by Jeselnik** [comment]
Hello & thank you for the suggestion.

I've added a new argument --non-interactive (-n for short) which accepts parameters "delete" (or "del") and "keep" which implements your feature request. Cheers for the interest in my program.

**Comment by TheBlackKoala** [comment]
Awesome! And thank you for making it. I was just about to make a script for it myself when i stumbled across yours and it works flawlessly! :)
