### ISSUE TITLE
Parsing begins at the wrong line

### ISSUE THREAD

**Issue by milomc123** [jeselnik/rb-scrobbler#4]
rb-scrobbler fails with the following error when attempting to scrobble:

```
panic: runtime error: index out of range [5] with length 1

goroutine 1 [running]:
main.logLineToTrack({0xc0001465c5?, 0xc0000120b0?}, {0x7ffc83584405, 0x3})
	/home/ed/repos/go/rb-scrobbler/src/log-functions.go:62 +0x2b8
main.main()
	/home/ed/repos/go/rb-scrobbler/src/rb-scrobbler.go:96 +0xcd8
```

This is due to the parser beginning on the wrong line of scrobbler.log. 

I believe this has something to do with Rockbox removing the lastfm scrobbling support from the OS and replacing it with a plugin in the latest versions.

This issue can be resolved by changing "FIRST_TRACK_LINE_INDEX" from 3 to 4 in the following file.

https://github.com/jeselnik/rb-scrobbler/blob/8243fb327bb56549e8a3835af4ea777bfd0e5fbe/cmd/rb-scrobbler.go#L17

Although, this will cause all scrobbler.log files generated with older versions of Rockbox to skip their first entry. Ideally, the parser should figure out where the data begins instead of relying on a hard coded value. This could probably be done by checking if the line begins with a hashtag.

I might have a go at a PR that fixes this, although I have absolutely no knowledge of Go so it may not be of particularly great quality :smile:

**Comment by milomc123** [comment]
Here is my scrobbler.log file that causes this issue. It was generated using a development build of Rockbox running on an iPod Video (5.5gen).
[scrobbler.log](https://github.com/jeselnik/rb-scrobbler/files/12052608/scrobbler.log)

**Comment by jeselnik** [comment]
Hi, thanks for bringing this to my attention. The solution I ended up with was to use some regex to ignore the various header lines. I've just pushed out a build after testing with an old style log & one from a rockbox nightly.
